#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, extname, join } from "node:path";
import { pathToFileURL } from "node:url";

const MIME_TYPE = "model/gltf-binary";

export async function convertGlbToJs(inputPath, outputPath = defaultOutputPath(inputPath)) {
  validateInputPath(inputPath);

  const glb = await readFile(inputPath);
  const base64 = glb.toString("base64");
  const source = renderModule({
    filename: basename(inputPath),
    base64
  });

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source, "utf8");
  return outputPath;
}

export function defaultOutputPath(inputPath) {
  const extension = extname(inputPath);
  const name = extension ? basename(inputPath, extension) : basename(inputPath);
  return join(dirname(inputPath), `${name}.js`);
}

function validateInputPath(inputPath) {
  if (!inputPath) {
    throw new Error("Usage: node tools/glb-to-js.mjs input.glb [output.js]");
  }

  if (extname(inputPath).toLowerCase() !== ".glb") {
    throw new Error("Input file must use the .glb extension.");
  }
}

function renderModule({ filename, base64 }) {
  return `// Generated by tools/glb-to-js.mjs. Do not edit by hand.
export const filename = ${JSON.stringify(filename)};
export const mimeType = ${JSON.stringify(MIME_TYPE)};
export const base64 = ${JSON.stringify(base64)};
export const dataUrl = \`data:\${mimeType};base64,\${base64}\`;

export default dataUrl;
`;
}

async function main(argv) {
  const [, , inputPath, outputPath] = argv;
  const writtenPath = await convertGlbToJs(inputPath, outputPath);
  process.stdout.write(`Wrote ${writtenPath}\n`);
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  main(process.argv).catch((error) => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
